services:
  mysql:
    image: mysql
    container_name: herogu-mysql
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-herogu-data:/var/lib/mysql
    env_file:
      - ../.env
    labels:
      tag: mysql

volumes:
  mysql-herogu-data: