services:
  back:
    image: ghcr.io/garage-isep/herogu-back/herogu-back:latest
    container_name: herogu-back
    tty: true
    expose:
      - 3000
    env_file:
      - app.env
    networks:
      - "web"
    restart: always
    volumes:
      - ./conf/github-private-key.pem:/app/github-private-key.pem
      - ./conf/mail.conf.json:/app/mail.conf.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Traefik configuration
      traefik.enable: 'true'
      traefik.http.routers.herogu-api-secure.rule: Host(`api.herogu.garageisep.com`)
      traefik.http.routers.herogu-api-secure.entrypoints: websecure
      traefik.http.routers.herogu-api-secure.tls.certresolver: myhttpchallenge
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      traefik.http.routers.herogu-api.rule: Host(`api.herogu.garageisep.com`)
      traefik.http.routers.herogu-api.entrypoints: web
      traefik.http.routers.herogu-api.middlewares: redirect
  front:
    image: ghcr.io/garage-isep/herogu-front/herogu-front:latest
    container_name: herogu-front
    tty: true
    expose:
      - 80
    networks:
      - "web"
    restart: always
    labels:
      # Traefik configuration
      traefik.enable: 'true'
      traefik.http.routers.herogu-front-secure.rule: Host(`herogu.garageisep.com`)
      traefik.http.routers.herogu-front-secure.entrypoints: websecure
      traefik.http.routers.herogu-front-secure.tls.certresolver: myhttpchallenge
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      traefik.http.routers.herogu-front.rule: Host(`herogu.garageisep.com`)
      traefik.http.routers.herogu-front.entrypoints: web
      traefik.http.routers.herogu-front.middlewares: redirect
  admin:
    image: ghcr.io/garage-isep/herogu-admin/herogu-admin:latest
    container_name: herogu-admin
    tty: true
    expose:
      - 80
    networks:
      - web
    restart: always
    labels:
      # Traefik configuration
      traefik.enable: 'true'
      traefik.http.routers.herogu-admin-secure.rule: Host(`admin.herogu.garageisep.com`)
      traefik.http.routers.herogu-admin-secure.entrypoints: websecure
      traefik.http.routers.herogu-admin-secure.tls.certresolver: myhttpchallenge
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      traefik.http.routers.herogu-admin.rule: Host(`admin.herogu.garageisep.com`)
      traefik.http.routers.herogu-admin.entrypoints: web
      traefik.http.routers.herogu-admin.middlewares: redirect

networks:
  web:
    external: true
